# -*- coding: utf-8 -*-
"""DecisionTree_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9LcZaoHJacAcbsGjZ-q1No7vgwjCC72
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import plot_tree

iris= sns.load_dataset("iris")
iris.head()

iris.info()

iris.shape

iris.isnull().any()

#We will plot pair plot to visualize the attributes
sns.pairplot(iris,hue="species")

print(iris.columns)
print(iris.dtypes)

#correlation matrix
# Select only numeric columns (exclude 'species')
numeric_columns = iris.select_dtypes(include=['float64', 'int64'])

# Now create the heatmap
sns.heatmap(numeric_columns.corr())
plt.show()

#Now we will separate target variable Y and features(X) as follows
target = iris["species"]
df1 = iris.copy()
df1 = df1.drop("species",axis=1)

#Defining the attributes
X=df1

target

#Label encoding as target variable is categorical
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
target = le.fit_transform(target)
target

y=target

#Splitting the dataset 80:20 ratio
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

# Now check the shapes
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")  # Should have same number of rows as X_train

#Defining the decision tree algorithm
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
print('Decision Tree classifier created')

#Predicting the values of the test data
from sklearn.metrics import classification_report
y_pred = dtree.predict(X_test)
print("Classification Report-\n")
print(classification_report(y_test,y_pred))

from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

# Visualize the Decision Tree
fig, axes = plt.subplots(1, 2, figsize=(20, 8))

from sklearn import tree
fn=['sepal_length','sepal_width','petal_length','petal_width']
cn=['setosa', 'versicolor', 'virginica']
fig,axes = plt.subplots(nrows=1,ncols= 1, figsize=(4, 4),dpi=500)
tree.plot_tree(dtree,
               feature_names=fn,
               class_names=cn,
               filled=True)
fig.savefig('treeimage.png')